illright/attractions

- src/card/card.scss
- src/card/card.svelte
- src/index.js
- src/var-defaults.scss
Image has been simplified as just a prop (instead of having to manually apply the `.image` class on it in the default slot). Title and subtitle have also been added as props
> Add Card component

- src/text-field/text-field.scss
- src/text-field/text-field.svelte
> Apply the main font to the label of an outlined text field

- src/button/button.svelte
- src/checkbox/checkbox.svelte
- src/chip/checkbox-chip.svelte
- src/chip/radio-chip.svelte
- src/radio-button/radio-button.svelte
- src/switch/switch.svelte
- src/text-field/text-field.svelte
> Pass the native event object along where applicable

- .github/workflows/pr_demo.yml
- package.json
- rollup.config.js
- yarn.lock
No CSS sourcemaps, minified JS in the demo. Not like we do any inspection in the demo anyway.
> Compress the demo

- src/button/button.scss
- src/file-input/file-dropzone.scss
- src/file-input/file-dropzone.svelte
- src/file-input/file-input.scss
- src/file-input/file-input.svelte
- src/star-rating/star-rating.scss
- src/star-rating/star-rating.svelte
Closes #30 
Turns out there was more to the problem than simply creating a focus state for the star rating.
> Focus and disabled states

- demo/App.svelte
- package.json
- src/_utils/datetime-utils.js
- src/_utils/range.js
- src/date-picker/date-picker.svelte
- src/index.js
- src/text-field/text-field.svelte
- src/time-picker/clock.svelte
- src/time-picker/time-picker.scss
- src/time-picker/time-picker.svelte
Decisions:
* no `range` version as the picker dropdown doesn't really get any more useful for the range, the users will simply put up two of those time pickers if they need a range
* no combined datetime picker, because, again, the dropdown doesn't benefit from this combination
> Time pickers

- demo/App.svelte
- demo/get-autocomplete-options.js
- src/_utils/call-on-sight.js
- src/autocomplete/autocomplete-field.scss
- src/autocomplete/autocomplete-field.svelte
- src/autocomplete/autocomplete-option.scss
- src/autocomplete/autocomplete-option.svelte
- src/autocomplete/autocomplete.scss
- src/autocomplete/autocomplete.svelte
- src/autocomplete/more-horizontal.svelte
- src/file-input/file-tile.scss
- src/form-field/form-field.scss
- src/index.js
- src/loading/loading.scss
- src/loading/loading.svelte
- src/text-field/text-field.scss
- src/typography/subhead.scss
- src/var-defaults.scss
Closes #19 
Was pretty reckless with this one, check for any console.logs or stuff like this
> Autocomplete

- LICENSE
- README.md
Yeah, and also change the copyright notice now that I'm 100% confident in what's supposed to be written there.
> Update the README with the installation instructions

- src/file-input/file-input.svelte
- src/modal/modal.svelte
* Allow clearing the file input through the `value` binding
* Allow listening to modal closing
> Miscellaneous improvements

- attractions/tab/tab.scss
Just internal style refactoring
> Allow restyling the tabs vertically

- attractions/form-field/form-field.svelte
Also allow passing the `id` for the `for` attribute
> Make the FormField use the proper label element

- .github/workflows/deploy.yml
- attractions/package.json
The scripts in the nested _attractions_ package were untested and caused problems when publishing
> Remove scripts and bump version

- .github/workflows/deploy.yml
Copy `README.md` to the attractions package being released to npm
> Copy the README when releasing to npm

- docs/src/routes/docs/installation.svx
- docs/static/css/components/docs/color-preview.scss
> Some fixes

- attractions/var-defaults.scss
- docs/src/routes/docs/_layout.svelte
Write out a ton of components in the menu to make sure that we can cleanly merge all the docs pages in parallel
> Scaffolding

- demo/package.json
- docs/package.json
- package.json
- yarn.lock
Fixes the security alert of `lodash`
> Bump the dependencies

- attractions/modal/modal.svelte
- docs/src/routes/docs/_layout.svelte
- docs/src/routes/docs/components/modal.svx
Breaking changes: Innopoints are still using the old interface, a PR to change it will follow.
> Document the Modal component

- docs/src/containers/home/info-tiles.svelte
- docs/src/routes/docs/index.svx
The horrible formatting is needed to remove extra space before the comma
> Request bundle size from BundlePhobia

- attractions/pagination/pagination.svelte
- attractions/text-field/text-field.svelte
- docs/src/routes/docs/components/text-field.svx
- docs/static/css/routes/docs/components/text-field.scss
Caution: insane suffering will be upon anyone who reviews this PR
> Document the TextField component

- attractions/package.json
- docs/src/routes/docs/installation.svx
- yarn.lock
Adds peer dependencies and mentions `var-defaults.scss`
> Docs: installation instructions

- README.md
This is how it will look like:
> Add badges for npm, bundlephobia, and Actions

- docs/src/routes/docs/components/checkbox-group.svx
- docs/src/routes/docs/components/radio-group.svx
> Add table header to style properties

- .eslintrc.js
- .github/workflows/deploy.yml
- .github/workflows/pr_demo.yml
- docs/src/components/docs/related-components.svelte
- docs/src/containers/home/info-tiles.svelte
- docs/static/css/prism-base16-tomorrow.css
- package.json
- Removes an unused job
- Adds a job to build the components and lint
> Refactor CI

- attractions/dropdown/dropdown-shell.svelte
- attractions/time-picker/time-picker.svelte
- docs/src/routes/docs/components/time-picker.svx
- The dropdown container will close when escape or return keys are pressed
- The time-picker has highlights current time and allows for custom labels
> Close on keypress and time highlighting

- attractions/utils/datetime-utils.js
> Fix the error from clearing the value of date and time pickers

- attractions/pagination/pagination.scss
- package.json
- yarn.lock
Following the directions on the official Husky docs
> Install Husky automatically

- attractions/autocomplete/autocomplete-option.svelte
- attractions/utils/escape-regexp.js
- attractions/utils/index.js
- docs/src/routes/docs/utilities.svx
> Escape the regexp in the autocomplete match highlighting

- attractions/autocomplete/autocomplete-field.svelte
> Fix the autocomplete options not showing up after selection

- attractions/file-input/file-tile.scss
- attractions/file-input/file-tile.svelte
> Fix the overflowing text on the file tiles

- docs/src/routes/docs/components/autocomplete-field.svx
- docs/src/routes/docs/components/autocomplete.svx
- docs/src/routes/docs/components/calendar.svx
- docs/src/routes/docs/components/checkbox-chip-group.svx
- docs/src/routes/docs/components/checkbox-group.svx
- docs/src/routes/docs/components/checkbox.svx
- docs/src/routes/docs/components/date-picker.svx
- docs/src/routes/docs/components/radio-button.svx
- docs/src/routes/docs/components/radio-chip-group.svx
- docs/src/routes/docs/components/radio-group.svx
- docs/src/routes/docs/components/tabs.svx
- docs/src/routes/docs/components/time-picker.svx
- docs/src/template.html
- docs/static/css/routes/docs/_layout.scss
> Merge SCSS variables from subcomponents

- docs/src/routes/docs/components/file-tile.svx
Just to not force the users to upload something before they can see the tile
> Show a JS-generated file to demo the file tile

- .eslintrc.js
- docs/src/components/docs/shadow-preview.svelte
- docs/static/css/components/docs/shadow-preview.scss
- package.json
More like work around, I still don't know what is causing this, perhaps I should file a bug to Sapper
> Fix the shadow previews not showing on page navigation

- docs/src/routes/docs/_layout.svelte
- docs/static/css/global.scss
- docs/static/css/routes/docs/_layout.scss
Currently it's just chilling at the bottom of the page, later on we'll make it pop up, get the focus right for accessibility, etc. All of that after I think about redesigning the docs
> Add a simple scroll to top button

- yarn.lock
To resolve the issues with syntax highlighting in the docs
> Regenerate the lock file

- .github/workflows/manual_deploy.yml
This is my attempt at writing an action for manual deployment. It'd be great to also pass `force_orphan` to the value opposite of `keep_files` but since those are strings, not booleans, idk how to invert its value.
> Add a workflow to manually deploy the docs

- .github/codeql/config.yml
- .github/workflows/codeql-analysis.yml
- docs/package.json
- package.json
Triggered on PRs to `main` or manually
> Add a CodeQL workflow

- .github/workflows/manual_deploy.yml
- .github/workflows/pr_docs.yml
- .github/workflows/release.yml
That's what's breaking the build
> Change the pinned version of peaceiris/actions-gh-pages to v3.7.3

- .github/workflows/auto-release.yml
And fix an embarassing case of undefined variables
> Exclude the line containing the version from the release body

- .github/workflows/deploy-pr-docs.yml
The files were renamed, but these 2 lines remained the same
> Fix workflow file name for downloading artifacts

- .github/workflows/build-pr-docs.yml
For reference: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#patterns-to-match-file-paths
> Fix path in Action to match nested folders

- CHANGELOG.md
- attractions/time-picker/time-picker.svelte
- docs/src/routes/docs/components/time-picker.svx
This also removes the coupling between minutes and seconds values
Closes #120
> Add hours, minutes, seconds props to time picker

- docs/src/components/docs/copyable-code.svelte
> Fix copyable in docs

- attractions/button/button.svelte
for better compatibility with SvelteKit
Closes #258
> Add `sveltekit:prefetch` to buttons

- attractions/package.json
- attractions/popover/popover-positions.js
- attractions/snackbar/snackbar-positions.js
- package.json
- pnpm-lock.yaml
Replace with `const` assertion.
Requires TypeScript 4.5+
> Refactor JSDoc duplicated types

- src/lib/button/button.svelte
- src/routes/docs/installation.svx
- src/routes/index.svelte
I'm sending this PR against the `sveltekit-migration` branch in https://github.com/illright/attractions/pull/349
> update Sapper references

- attractions/slider/slider.svelte
- attractions/slider/utils.js
Fix for https://github.com/illright/attractions/issues/379
> Don't check slider position on mouseup or touchend events

- .github/workflows/auto-release.yml
- .github/workflows/build-pr-docs.yml
- .github/workflows/deploy-pr-docs.yml
- .github/workflows/lint-pr.yml
- .github/workflows/manual-deploy.yml
- .github/workflows/on-release.yml
- .github/workflows/suggest-release.yml
- package.json
- pnpm-lock.yaml
-----
<a href="https://stackblitz.com/~/github.com/illright/attractions/tree/illright/patch-51869"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/illright/attractions/tree/illright/patch-51869)._
> Upgrade workflows

- .github/workflows/on-release.yml
-----
<a href="https://stackblitz.com/~/github.com/illright/attractions/tree/illright/patch-53704"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz" align="left" width="103" height="20"></a> _Submitted with [StackBlitz](https://stackblitz.com/~/github.com/illright/attractions/tree/illright/patch-53704)._
> Allow workflow dispatch for release chores
