src/snackbar/snackbar-container.svelte, src/snackbar/snackbar.svelte
This will return a promise that resolves when the snackbar is closed. From that one can deduce if the snackbar expired or was closed manually (perhaps with the snackbar action). Useful for situations like undo actions
=> Give information about the nature of the snackbar disappearing

src/snackbar/snackbar-container.svelte
This is to be able to use this function in the same component where the `SnackbarContainer` is defined (so context and the slot props are not available). One just needs to bind:this to some variable and call the `showSnackbar` method on that variable.
=> Export the showSnackbar function

attractions/text-field/text-field.svelte
This one is needed because previously empty `<TextField type="number">` elements would send a warning to the console saying that it cannot parse NaN, which is a result of some messy handling.
=> Fix the value handling for TextFields of type="number"

attractions/_utils/datetime-utils.js, attractions/date-picker/date-picker.svelte, attractions/time-picker/time-picker.svelte
First of all, it was mutating the value, which kinda interferes with the traditional communication methods via `bind:` or `on:change`. It also meant that you couldn't avoid the date change, which is no good.
Second, this will open the date picker calendar on the month of the selection (something that should've been there in the first place).
=> Fixes around the date picker

attractions/autocomplete/autocomplete-field.svelte, attractions/autocomplete/autocomplete.scss, demo/get-autocomplete-options.js
Apparently, returning a value from a generator not only looks ugly, but also causes issues with stuff like generator delegation. In Innopoints I had an async generator that was returning the last value, as opposed to yielding it and then returning `undefined`. And apparently in some cases the returned value of generators is ignored, for instance, in `for ... of` loops and generator delegation. This will allow returning `undefined` (and this should be the best practice for this function)
=> Refactor the Autocomplete to ignore the return of the generator

attractions/snackbar/snackbar.svelte
In some cases one only wants the snackbar action to close it (in order to force some action, as in `undo`, for example, would _actually_ do the action after the snackbar expires).
=> Allow omitting the callback in the snackbar action

attractions/file-input/file-dropzone.scss, attractions/file-input/file-dropzone.svelte, attractions/file-input/file-tile.svelte
UPD: we're talking about the FileDropzone component here
In the case of Innopoints, this could mean starting the upload so that a Promise with the ID exists. It also supports exceptions, so if a file is invalid for some reason (filename or size), an exception can be thrown in that function and this file will not be added.
=> Allow passing a function to be called before file acceptance

attractions/modal/modal.svelte
I deliberately opted for a certain amount of code duplication to prevent from messing around with the code structure + remove an event listener when it's not used
=> Allow disabling the clickaway behaviour of the modal overlay

docs/src/components/home/info-tile.svelte, docs/src/containers/home/info-tiles.svelte, docs/static/css/components/home/info-tile.scss
The other day I was told (and witnessed how someone kept pressing the tiles) that the tiles look like something you should click, so they completely overlooked the buttons (through the mobile version, anyway).
So I figured, why not. The links for the first two tiles are kind of best-fit, I think it's worth having a separate page listing all the components in the future, which can be an optimal destination for the first tile, and we should also have a separate list of all SCSS variables, where the second tile will be linking. In the meantime,
=> Make the tiles on the home page capable of navigation

CHANGELOG.md, attractions/date-picker/date-picker.svelte
Previously the DatePicker was built with a `bool` event detail, which was changed to `{ value }` at some point. This will fix the focusing bug.
Closes #138
=> Update the dropdown event interface

.github/workflows/pr_demo.yml
The docs say it should run the CI based on our code, not the fork's which will make the token read-write and allow publishing to GH Pages
=> Change the trigger to pull_request_target

.github/workflows/pr_docs.yml
Since the official actions/download-artifact only works within the same workflow
This Action should be able to download the artifact from a different workflow
=> Use a download action that supports cross-workflow

CHANGELOG.md, attractions/date-picker/calendar.svelte
Bug: if you go to November 2020 and click on the grayed out 1st of December, the dropdown will close, though it shouldn't
=> Fix the DatePicker closing when months have different week numbers

attractions/autocomplete/autocomplete-field.svelte, attractions/autocomplete/autocomplete.scss, attractions/autocomplete/autocomplete.svelte
Previously we were forwarding slots from `AutocompleteField` to `Autocomplete` which essentially works by creating a new slot and providing the content of that slot to the old one, effectively never giving it a chance to render its default. This is a little dirty but it works.
You might also notice that one slot had to be wrapped in an extra DOM element, that's because you cannot forward slot props properly (sigh), in other words, something like this is not possible (and wouldn't seem logical either):
```svelte
<slot slot="smth" name="smth" let:prop {prop} />
```
=> Copy over the slot defaults from AutocompleteField to Autocomplete

.github/workflows/deploy.yml
Not sure if that would help with the memory, but the last PR had built successfully for the branch action, so it should be possible with GitHub Actions
=> Update the Node version for the release builds

.github/workflows/pr_docs.yml
Previously, it would query the last successful run and use its results
This caused it to use old artifacts and comment on irrelevant PRs
=> Only deploy docs if previous workflow succeeded

CHANGELOG.md, attractions/snackbar/snackbar-container.svelte
Not like this is very public API or a commonly used feature, but I figured why not.
Closes #216
=> Allow passing the `closeCallback` for snackbars

docs/src/routes/docs/installation.svx
Importing `svelte.config.js` with an ES6 import doesn't work for some reason.
Related to #240
=> Fix the import style in the docs

attractions/utils/datetime-utils.js
- Create day cursor in local timezone
For more discussion see #243
=> Bug: fix getCalendar day cursor in short months

attractions/_appearances.scss, attractions/_variables.scss, attractions/text-field/text-field.scss, docs/src/routes/docs/components/button.svx, docs/src/routes/docs/components/text-field.svx
* Introduces a new variable, `$button-font-weight`, to allow changing the `font-weight` of a `<Button>`.
* Introduces a new variable, `$textfield-outline-radius`, to allow changing the `border-radius` of a `<TextField outline>`.
* ~~Introduces a new variable, `$textfield-outline-label-bg`, to allow changing the `background-color` of a `label` in a `<TextField outline>`.~~
* Closes #245 
* Closes #246
=> Adds variables to customize buttons & textfield outline

CHANGELOG.md, attractions/date-picker/date-picker.svelte, attractions/time-picker/time-picker.svelte, docs/src/routes/docs/components/date-picker.svx, docs/src/routes/docs/components/time-picker.svx, package.json
So that they can be passed down to the `TextField` inside.
Resolves #269
=> Add the inputClass prop to TimePicker & DatePicker

attractions/dropdown/dropdown-shell.svelte, attractions/snackbar/snackbar-container.svelte
Sveld has been updated and they are no longer detected as props.
The `@readonly` annotation was still preventing it from detecting properly.
=> Fix the types of exported functions

CHANGELOG.md, attractions/_variables.scss, attractions/breadcrumbs/breadcrumbs.scss, attractions/index.js, attractions/table/table.scss, attractions/table/table.svelte, docs/src/routes/docs/_layout.svelte, docs/src/routes/docs/components/table.svx
The component was directly taken from the docs, with a few added props and slots.
I am also thinking that:
1- slots should be inside the `th`/`tr`/`td`, not replace them (to preserve proper semantics and avoid mistakes by forgetting to add the wrapping element)
2- the `header` slot should be like the `item` one in that it replaces just one header (which it takes as a prop) and not the entire row. Or should we make both slots?
And I feel that the wording in the docs can be improved a bit.
Closes #255
=> Create a `Table` component

.github/workflows/on-release.yml
It was breaking releases due to the copying of README and LICENSE files
=> Add `--no-git-checks` to `pnpm publish`

attractions/card/card.scss
Minor fix to adapt `card`'s background to use the theme background variable instead of using an absolute value.
=> Change from absolute color to scss varaible

CHANGELOG.md, attractions/autocomplete/autocomplete-field.svelte, attractions/autocomplete/autocomplete.svelte, attractions/checkbox/checkbox-group.svelte, attractions/chip/checkbox-chip-group.svelte, attractions/chip/radio-chip-group.svelte, attractions/package.json, attractions/radio-button/radio-group.svelte, docs/package.json, pnpm-lock.yaml
Update component `@extends` annotations and relative type imports to add the `.svelte` extension to align with the changes in [sveld v0.10.0](https://github.com/carbon-design-system/sveld/blob/main/CHANGELOG.md#0100---2021-08-28).
Fixes #325
=> Hotfix: sveld-generated types

CHANGELOG.md, attractions/package.json, attractions/time-picker/time-picker.svelte, docs/src/routes/docs/components/time-picker.svx
This pull-request closes #330 
I hope everything looks good. The documentation compiled locally without any problems. Tell me if I need to change the description of the prop.
=> Add hideNow prop to time-picker

attractions/autocomplete/autocomplete-field.svelte, attractions/autocomplete/autocomplete.svelte, attractions/date-picker/calendar.svelte, attractions/file-input/file-dropzone.svelte, attractions/file-input/file-input.svelte, attractions/form-field/form-field.svelte, docs/src/routes/docs/components/autocomplete-field.svx, docs/src/routes/docs/components/calendar.svx, docs/src/routes/docs/components/file-dropzone.svx, docs/src/routes/docs/components/file-input.svx, docs/src/routes/docs/components/form-field.svx
This issue allows to add slots to be able to translate the messages of the components. 
Close #315 
- Line 142: "close the options": `close-message`
- Line 169: "Loading": `loading-message`
- Line 193: "load more options": `load-more-options-message`
- Line 101: "Loading": `loading-message`
- Line 193: "load more options": `load-more-options-message`
- Line 77: "Today, not available": `titleTodayNotAvailableMessage` (props)
- Line 79: "Today": `titleTodayMessage` (props)
- Line 84: "Not available": `titleTodayMessage` (props)
- Line 128: "file upload unavailable": `upload-unavailable-message`
- Line 130: "incorrect file type": `incorrect-file-message`
- Line 132: "release to upload": `release-to-upload-message`
- Line 134: "drag &amp; drop here or click to upload files": …
=> Add slots for translation

attractions/autocomplete/autocomplete-option.svelte, attractions/file-input/file-dropzone.svelte, attractions/modal/modal.svelte
Svelte compiler complains about non-interactive elements with on:click handlers not having a keyboard alternative  for a11y purposes.
This change adds missing event handlers.
=> Prevent svelte compiler from throwing accessibility warnings where we only care about the click event
